### ISSUE TITLE
note about NC_precinct_general.zip

### ISSUE THREAD

**Issue by rootsmusic** [MEDSL/2020-elections-official#3]
@jcuriel-unc Please note that this file is pulled from NCSBE's [unsorted results](https://s3.amazonaws.com/dl.ncsbe.gov/ENRS/2020_11_03/results_pct_20201103.zip).  Since its "mode" column doesn't identify TRANSFER ballots, its "votes" column is unsorted in terms of TRANSFER ballots.  Sorted precinct results are at https://s3.amazonaws.com/dl.ncsbe.gov/ENRS/2020_11_03/results_precinct_sort/STATEWIDE_PRECINCT_SORT.txt

**Comment by declanc2021** [comment]
@rootsmusic We are currently working on incorporating the data with TRANSFER mode into our repository. Thank you for flagging.

**Comment by rootsmusic** [comment]
You're welcome, @declanc2021.  Please update this issue if you've finished revising this file.  Is this repo on https://electionlab.mit.edu/data ?

**Comment by declanc2021** [comment]
@rootsmusic Thank you for your patience. We have just added the data as a separate csv file to the individual_states folder within this repository (../main/individual_states/2020-nc-precinct-general.zip). We included some information about the data in the "North Carolina" section of the README.md.

**Comment by rootsmusic** [comment]
Ok @declanc2021, you may have noticed 2020-nc-precinct-general-transfer.csv included votes that didn't complete the sorting process.  Hence, these unsorted votes weren't added to any precinct's sorted votes ("ELECTION DAY - TRANSFER" mode).  The unsorted votes were in rows where the precinct column had values that don't match real precinct codes.  Does MEDSL plan to disaggregate the unsorted votes from county-level to real precincts by interpolation to another file?

**Comment by declanc2021** [comment]
@rootsmusic We do not plan on doing that at this time. We are reporting the data as provided by NCSBE in our common data format.
